### ISSUE TITLE
Greenland is cut off and Antarctica is missing

### ISSUE THREAD

**Issue by rene-mueller** [wipfli/esa-worldcover-polygons#3]
![grafik](https://github.com/wipfli/esa-worldcover-polygons/assets/48084558/f9ad7025-1523-4487-8946-2a2d225c58e4)

**Comment by rene-mueller** [comment]
Here you can see it better again:

![grafik](https://github.com/wipfli/esa-worldcover-polygons/assets/48084558/0101952a-ed59-4e55-9044-bb8ce64a5669)

**Comment by wipfli** [comment]
That looks like a limitation of the original ESA dataset. Not also that Antarctica is cut-off.

We could use the natural earth land/water polygons and just say that everything North of x deg or South of -x deg is of class Snow and Ice. What do you think?

**Comment by rene-mueller** [comment]
yep its a limitation of the original ESA dataset. I'll found the following dataset: https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-glaciated-areas/

It contains all Snow and Ice areas:
<img width="1113" alt="grafik" src="https://github.com/wipfli/esa-worldcover-polygons/assets/48084558/b76e5038-f2fb-4051-b333-3721d37c0904">

So we could use the data of it and remove snow and ice from the esa data :)

**Comment by rene-mueller** [comment]
@wipfli with the styling it can be done like this: https://docs.mapbox.com/mapbox-gl-js/example/style-ocean-depth-data/

**Comment by wipfli** [comment]
Feel free to give the ne vectors a try.
