### ISSUE TITLE
Replace single water layer with natural earth data

### ISSUE THREAD

**Issue by rene-mueller** [wipfli/esa-worldcover-polygons#4]
Remove generation of water layer and add natural earth data instead.

possibly the following articles can help as well:

* https://documentation.maptiler.com/hc/en-us/articles/9818655484433-How-to-build-an-ocean-vector-bathymetry-map-with-MapTiler
* https://medium.com/nightingale/styling-ocean-depth-data-in-mapbox-studio-c03f71ba6a2a

In association with: https://github.com/onthegomap/planetiler/issues/9

**Comment by wipfli** [comment]
Sounds like a good idea to have better water outlines. I think the Meta map style also has some nice bathymetry so it might be worth asking them how they did it...

**Comment by rene-mueller** [comment]
That's right. I've read that they also use [naturalearthdata](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-bathymetry/). The advantage of naturalearthdata is that it does not require attribution. :)

**Comment by rene-mueller** [comment]
@wipfli with the styling it can be done like this: https://docs.mapbox.com/mapbox-gl-js/example/style-ocean-depth-data/

**Comment by rene-mueller** [comment]
@wipfli what do you think about my first result:
<img width="844" alt="grafik" src="https://github.com/wipfli/esa-worldcover-polygons/assets/48084558/a20a0cd1-8f49-4541-a60a-d48ec926753f">

**Comment by wipfli** [comment]
I think it looks beautiful

**Comment by rene-mueller** [comment]
@wipfli i have only one problem:

When the poligons merge, the following happens:
<img width="914" alt="grafik" src="https://github.com/wipfli/esa-worldcover-polygons/assets/48084558/d287cff1-9e20-43fc-b705-a18c9073fb61">
<img width="1076" alt="grafik" src="https://github.com/wipfli/esa-worldcover-polygons/assets/48084558/23badc48-80da-4741-8397-77760a1c7118">

Can you eventually help?

**Comment by msbarry** [comment]
Looks like the issue is that the bathymetry polygons are sorted randomly. Best would be to sort them in the tiles by using `setSortKey(depth)` on the polygons to draw deeper ones on top of shallower ones.  You could also do it client-side by adding `layout: {'fill-sort-key': ['get', 'depth']}` but doing it at generation time would save some work on the client.

**Comment by rene-mueller** [comment]
@msbarry thank you, it worked :)

**Comment by laem** [comment]
Hi ! I'm wondering if a bathymetry pmtiles file is available somewhere ? I'd like to add them to MapLibre's new globe capability.

**Comment by wipfli** [comment]
@laem thanks for asking. I think you can download https://pub-726b01260c98468a9387cc0dfcb7386b.r2.dev/esa-worldcover-polygons.pmtiles and then get the bathy layer out of this. We had bathy in v1 and removed it in v2.

**Comment by laem** [comment]
Thanks ! Finally got it working at https://dev.cartes.app :) It's beautiful.

**Comment by wipfli** [comment]
Oh nice, congrats!

**Comment by wipfli** [comment]
Do you use https://github.com/wipfli/h3-landcover as well?

**Comment by laem** [comment]
Yes ! Should I credit the project in the bottom-right credits ? By your name ? 
![image](https://github.com/user-attachments/assets/89fd1440-9a09-4427-9969-8812568ed2d0)

And thanks for your work, by the way.

**Comment by wipfli** [comment]
Nice. Attribution is not required, all fine the way it is now!
